// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package chat

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ItemKey struct {
	Index                int32    `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemKey) Reset()         { *m = ItemKey{} }
func (m *ItemKey) String() string { return proto.CompactTextString(m) }
func (*ItemKey) ProtoMessage()    {}
func (*ItemKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *ItemKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemKey.Unmarshal(m, b)
}
func (m *ItemKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemKey.Marshal(b, m, deterministic)
}
func (m *ItemKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemKey.Merge(m, src)
}
func (m *ItemKey) XXX_Size() int {
	return xxx_messageInfo_ItemKey.Size(m)
}
func (m *ItemKey) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemKey.DiscardUnknown(m)
}

var xxx_messageInfo_ItemKey proto.InternalMessageInfo

func (m *ItemKey) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type ItemValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemValue) Reset()         { *m = ItemValue{} }
func (m *ItemValue) String() string { return proto.CompactTextString(m) }
func (*ItemValue) ProtoMessage()    {}
func (*ItemValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *ItemValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemValue.Unmarshal(m, b)
}
func (m *ItemValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemValue.Marshal(b, m, deterministic)
}
func (m *ItemValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemValue.Merge(m, src)
}
func (m *ItemValue) XXX_Size() int {
	return xxx_messageInfo_ItemValue.Size(m)
}
func (m *ItemValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemValue.DiscardUnknown(m)
}

var xxx_messageInfo_ItemValue proto.InternalMessageInfo

func (m *ItemValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Item struct {
	Key                  *ItemKey   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *ItemValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetKey() *ItemKey {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Item) GetValue() *ItemValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*ItemKey)(nil), "chat.ItemKey")
	proto.RegisterType((*ItemValue)(nil), "chat.ItemValue")
	proto.RegisterType((*Item)(nil), "chat.Item")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xce, 0x48, 0x2c,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xe4, 0xb9, 0xd8, 0x3d, 0x4b,
	0x52, 0x73, 0xbd, 0x53, 0x2b, 0x85, 0x44, 0xb8, 0x58, 0x33, 0xf3, 0x52, 0x52, 0x2b, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x58, 0x83, 0x20, 0x1c, 0x25, 0x45, 0x2e, 0x4e, 0x90, 0x82, 0xb0, 0xc4, 0x9c,
	0xd2, 0x54, 0x90, 0x92, 0x32, 0x10, 0x03, 0xac, 0x84, 0x33, 0x08, 0xc2, 0x51, 0xf2, 0xe3, 0x62,
	0x01, 0x29, 0x11, 0x92, 0xe7, 0x62, 0xce, 0x4e, 0xad, 0x04, 0xcb, 0x71, 0x1b, 0xf1, 0xea, 0x81,
	0xed, 0x82, 0x1a, 0x1e, 0x04, 0x92, 0x11, 0x52, 0x85, 0x69, 0x67, 0x02, 0x2b, 0xe1, 0x47, 0x28,
	0x01, 0x1b, 0x0f, 0x35, 0xcf, 0xc8, 0x98, 0x8b, 0xc5, 0x39, 0x23, 0xb1, 0x44, 0x48, 0x9b, 0x8b,
	0xdd, 0x3d, 0xb5, 0x04, 0x6c, 0x34, 0xaa, 0x69, 0x52, 0xe8, 0x3a, 0x95, 0x18, 0x92, 0xd8, 0xc0,
	0xbe, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x8e, 0xf1, 0x24, 0x64, 0xe3, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatClient interface {
	GetItem(ctx context.Context, in *ItemKey, opts ...grpc.CallOption) (*ItemValue, error)
}

type chatClient struct {
	cc *grpc.ClientConn
}

func NewChatClient(cc *grpc.ClientConn) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) GetItem(ctx context.Context, in *ItemKey, opts ...grpc.CallOption) (*ItemValue, error) {
	out := new(ItemValue)
	err := c.cc.Invoke(ctx, "/chat.Chat/GetItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServer is the server API for Chat service.
type ChatServer interface {
	GetItem(context.Context, *ItemKey) (*ItemValue, error)
}

// UnimplementedChatServer can be embedded to have forward compatible implementations.
type UnimplementedChatServer struct {
}

func (*UnimplementedChatServer) GetItem(ctx context.Context, req *ItemKey) (*ItemValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItem not implemented")
}

func RegisterChatServer(s *grpc.Server, srv ChatServer) {
	s.RegisterService(&_Chat_serviceDesc, srv)
}

func _Chat_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ItemKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chat.Chat/GetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetItem(ctx, req.(*ItemKey))
	}
	return interceptor(ctx, in, info, handler)
}

var _Chat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetItem",
			Handler:    _Chat_GetItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
